runtime: nodejs18
handlers:
  # Serve all static files with urls ending with a file extension
- url: /(.*\..+)$ 
  static_files: lib/dist/\1
  upload: lib/dist/(.*\..+)$
  # catch all handler to index.html
- url: /.*
  static_files: lib/dist/index.html
  upload: lib/dist/index.html