steps:
- name: node:16.x.x
  entrypoint: npm
  args: ["install"]
- name: node:16.x.x
  entrypoint: npm
  args: ["run", "build"]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ["app", "deploy"]
timeout: "1600s"
options:
  logging: CLOUD_LOGGING_ONLY