steps:
# - name: node:18.12.0
#   entrypoint: npm
#   args: ["install"]
# - name: node:18.12.0
#   entrypoint: npm
#   args: ["run", "build"]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ["app", "deploy"]
timeout: "1600s"
options:
  logging: CLOUD_LOGGING_ONLY